CRITICAL - 2024-07-29 06:17:57 --> ErrorException: Undefined variable $con
[Method: GET, Route: add]
in APPPATH\Views\addpage.php on line 26.
 1 APPPATH\Views\addpage.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $con', 'C:\\xampp\\htdocs\\task\\app\\Views\\addpage.php', 26)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\task\\app\\Views\\addpage.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('addpage', [], true)
 5 APPPATH\Controllers\Home.php(24): view('addpage')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->add()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 06:20:26 --> ErrorException: Undefined array key "title"
[Method: GET, Route: add]
in APPPATH\Views\addpage.php on line 40.
 1 APPPATH\Views\addpage.php(40): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "title"', 'C:\\xampp\\htdocs\\task\\app\\Views\\addpage.php', 40)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\task\\app\\Views\\addpage.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('addpage', [], true)
 5 APPPATH\Controllers\Home.php(24): view('addpage')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->add()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 06:41:28 --> ErrorException: Undefined property: stdClass::$mobile_number
[Method: POST, Route: getData]
in APPPATH\Controllers\Home.php on line 60.
 1 APPPATH\Controllers\Home.php(60): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$mobile_number', 'C:\\xampp\\htdocs\\task\\app\\Controllers\\Home.php', 60)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->getData()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 06:42:20 --> ErrorException: Undefined property: stdClass::$mobile_number
[Method: POST, Route: getData]
in APPPATH\Controllers\Home.php on line 60.
 1 APPPATH\Controllers\Home.php(60): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$mobile_number', 'C:\\xampp\\htdocs\\task\\app\\Controllers\\Home.php', 60)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->getData()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 06:42:21 --> ErrorException: Undefined property: stdClass::$mobile_number
[Method: POST, Route: getData]
in APPPATH\Controllers\Home.php on line 60.
 1 APPPATH\Controllers\Home.php(60): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$mobile_number', 'C:\\xampp\\htdocs\\task\\app\\Controllers\\Home.php', 60)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->getData()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-29 09:33:54 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost:3309', 'root', Object(SensitiveParameterValue), 'data_table', 3306, '', 0)
#1 C:\xampp\htdocs\task\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\task\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\task\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\task\app\Controllers\Home.php(100): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\task\system\CodeIgniter.php(933): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\task\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\task\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\task\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\task\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\task\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\task\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\task\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\task\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\task\app\Controllers\Home.php(100): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\task\system\CodeIgniter.php(933): App\Controllers\Home->getData()
#5 C:\xampp\htdocs\task\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\task\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\task\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\task\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 C:\xampp\htdocs\task\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
CRITICAL - 2024-07-29 09:33:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: getData]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `datatable_2`', [], false)
 3 APPPATH\Controllers\Home.php(100): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->getData()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 09:33:58 --> mysqli_sql_exception: No connection could be made because the target machine actively refused it
[Method: GET, Route: add]
in APPPATH\Views\addpage.php on line 30.
 1 APPPATH\Views\addpage.php(30): mysqli_connect('localhost:3309', 'root', Object(SensitiveParameterValue), 'test')
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\task\\app\\Views\\addpage.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('addpage', [], true)
 5 APPPATH\Controllers\Home.php(24): view('addpage')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->add()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-29 09:34:33 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost:3309', 'root', Object(SensitiveParameterValue), 'data_table', 3306, '', 0)
#1 C:\xampp\htdocs\task\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\task\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\task\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\task\app\Controllers\Home.php(100): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\task\system\CodeIgniter.php(933): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\task\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\task\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\task\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\task\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\task\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\task\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\task\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\task\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\task\app\Controllers\Home.php(100): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\task\system\CodeIgniter.php(933): App\Controllers\Home->getData()
#5 C:\xampp\htdocs\task\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\task\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\task\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\task\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 C:\xampp\htdocs\task\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
CRITICAL - 2024-07-29 09:34:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: getData]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `datatable_2`', [], false)
 3 APPPATH\Controllers\Home.php(100): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->getData()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-29 09:35:11 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost:3309', 'root', Object(SensitiveParameterValue), 'data_table', 3306, '', 0)
#1 C:\xampp\htdocs\task\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\task\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\task\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\task\app\Controllers\Home.php(100): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\task\system\CodeIgniter.php(933): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\task\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\task\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\task\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\task\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\task\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\task\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\task\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\task\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\task\app\Controllers\Home.php(100): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\task\system\CodeIgniter.php(933): App\Controllers\Home->getData()
#5 C:\xampp\htdocs\task\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\task\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\task\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\task\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 C:\xampp\htdocs\task\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
CRITICAL - 2024-07-29 09:35:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: getData]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`', [], false)
 3 APPPATH\Controllers\Home.php(100): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->getData()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 09:35:12 --> mysqli_sql_exception: No connection could be made because the target machine actively refused it
[Method: GET, Route: add]
in APPPATH\Views\addpage.php on line 30.
 1 APPPATH\Views\addpage.php(30): mysqli_connect('localhost:3309', 'root', Object(SensitiveParameterValue), 'test')
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\task\\app\\Views\\addpage.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('addpage', [], true)
 5 APPPATH\Controllers\Home.php(24): view('addpage')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->add()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 09:35:33 --> mysqli_sql_exception: No connection could be made because the target machine actively refused it
[Method: GET, Route: add]
in APPPATH\Views\addpage.php on line 30.
 1 APPPATH\Views\addpage.php(30): mysqli_connect('localhost:3309', 'root', Object(SensitiveParameterValue), 'test')
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\task\\app\\Views\\addpage.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('addpage', [], true)
 5 APPPATH\Controllers\Home.php(24): view('addpage')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->add()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-29 09:36:35 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'user' in C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'user', 3306, '', 0)
#1 C:\xampp\htdocs\task\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\task\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\task\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\task\app\Controllers\Home.php(100): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\task\system\CodeIgniter.php(933): App\Controllers\Home->getData()
#6 C:\xampp\htdocs\task\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\task\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\task\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\task\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\task\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'user' in C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\task\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\task\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\task\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\task\app\Controllers\Home.php(100): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\task\system\CodeIgniter.php(933): App\Controllers\Home->getData()
#5 C:\xampp\htdocs\task\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\task\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\task\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\task\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 C:\xampp\htdocs\task\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
CRITICAL - 2024-07-29 09:36:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'user'
[Method: POST, Route: getData]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`', [], false)
 3 APPPATH\Controllers\Home.php(100): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->getData()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 09:36:41 --> mysqli_sql_exception: No connection could be made because the target machine actively refused it
[Method: GET, Route: add]
in APPPATH\Views\addpage.php on line 30.
 1 APPPATH\Views\addpage.php(30): mysqli_connect('localhost:3309', 'root', Object(SensitiveParameterValue), 'test')
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\task\\app\\Views\\addpage.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('addpage', [], true)
 5 APPPATH\Controllers\Home.php(24): view('addpage')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->add()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 09:39:19 --> ErrorException: Undefined property: stdClass::$refer_id
[Method: POST, Route: getData]
in APPPATH\Controllers\Home.php on line 111.
 1 APPPATH\Controllers\Home.php(111): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$refer_id', 'C:\\xampp\\htdocs\\task\\app\\Controllers\\Home.php', 111)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->getData()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-29 09:40:52 --> mysqli_sql_exception: Unknown column 'refer_id' in 'field list' in C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\task\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\task\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\task\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\task\app\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\task\system\CodeIgniter.php(933): App\Controllers\Home->addData()
#6 C:\xampp\htdocs\task\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\task\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\task\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\task\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\task\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-29 09:40:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'refer_id' in 'field list'
[Method: POST, Route: addData]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (:name:, :user_id:, :amount:, :balance:, :calculation:, :refer_id:)', [...], false)
 2 APPPATH\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addData()
 4 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 09:40:52 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'refer_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (:name:, :user_id:, :amount:, :balance:, :calculation:, :refer_id:)', [...], false)
 4 APPPATH\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addData()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 09:40:52 --> [Caused by] mysqli_sql_exception: Unknown column 'refer_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (:name:, :user_id:, :amount:, :balance:, :calculation:, :refer_id:)', [...], false)
 5 APPPATH\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addData()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-29 09:41:14 --> mysqli_sql_exception: Unknown column 'refer_id' in 'field list' in C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\task\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\task\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\task\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\task\app\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\task\system\CodeIgniter.php(933): App\Controllers\Home->addData()
#6 C:\xampp\htdocs\task\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\task\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\task\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\task\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\task\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-29 09:41:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'refer_id' in 'field list'
[Method: POST, Route: addData]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (:name:, :user_id:, :amount:, :balance:, :calculation:, :refer_id:)', [...], false)
 2 APPPATH\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addData()
 4 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 09:41:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'refer_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Gowtham\', \'user-001\', \'100\', \'100\', \'Gowtham = 100 + 10%(0) + 10%(0)\', \'-\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Gowtham\', \'user-001\', \'100\', \'100\', \'Gowtham = 100 + 10%(0) + 10%(0)\', \'-\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (:name:, :user_id:, :amount:, :balance:, :calculation:, :refer_id:)', [...], false)
 4 APPPATH\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addData()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 09:41:14 --> [Caused by] mysqli_sql_exception: Unknown column 'refer_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Gowtham\', \'user-001\', \'100\', \'100\', \'Gowtham = 100 + 10%(0) + 10%(0)\', \'-\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Gowtham\', \'user-001\', \'100\', \'100\', \'Gowtham = 100 + 10%(0) + 10%(0)\', \'-\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Gowtham\', \'user-001\', \'100\', \'100\', \'Gowtham = 100 + 10%(0) + 10%(0)\', \'-\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (:name:, :user_id:, :amount:, :balance:, :calculation:, :refer_id:)', [...], false)
 5 APPPATH\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addData()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-29 09:42:47 --> mysqli_sql_exception: Unknown column 'refer_id' in 'field list' in C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\task\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\task\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\task\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\task\app\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\task\system\CodeIgniter.php(933): App\Controllers\Home->addData()
#6 C:\xampp\htdocs\task\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\task\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\task\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\task\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\task\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-29 09:42:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'refer_id' in 'field list'
[Method: POST, Route: addData]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (:name:, :user_id:, :amount:, :balance:, :calculation:, :refer_id:)', [...], false)
 2 APPPATH\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addData()
 4 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 09:42:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'refer_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (:name:, :user_id:, :amount:, :balance:, :calculation:, :refer_id:)', [...], false)
 4 APPPATH\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addData()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 09:42:47 --> [Caused by] mysqli_sql_exception: Unknown column 'refer_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (:name:, :user_id:, :amount:, :balance:, :calculation:, :refer_id:)', [...], false)
 5 APPPATH\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addData()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-29 09:43:29 --> mysqli_sql_exception: Unknown column 'refer_id' in 'field list' in C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\task\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\task\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\task\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\task\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\task\app\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\task\system\CodeIgniter.php(933): App\Controllers\Home->addData()
#6 C:\xampp\htdocs\task\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\task\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\task\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\task\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\task\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-29 09:43:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'refer_id' in 'field list'
[Method: POST, Route: addData]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (:name:, :user_id:, :amount:, :balance:, :calculation:, :refer_id:)', [...], false)
 2 APPPATH\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addData()
 4 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 09:43:29 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'refer_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (:name:, :user_id:, :amount:, :balance:, :calculation:, :refer_id:)', [...], false)
 4 APPPATH\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addData()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-07-29 09:43:29 --> [Caused by] mysqli_sql_exception: Unknown column 'refer_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (\'Yogesh\', \'user-001\', \'100\', \'100\', \'Yogesh = 100 + 10%(0) + 10%(0)\', \'-\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `user_id`, `amount`, `balance`, `calculation`, `refer_id`) VALUES (:name:, :user_id:, :amount:, :balance:, :calculation:, :refer_id:)', [...], false)
 5 APPPATH\Controllers\Home.php(84): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addData()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
